services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ex-pressa-app
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      ENV_FILE: .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '${PORT}:3000'

  postgres:
    image: postgres:16-alpine
    container_name: ex-pressa-postgres
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ex-pressa-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  ex-pressa-pgdata:
